### ISSUE TITLE
Statistic 

### ISSUE THREAD

**Issue by wangbo9719** [allenai/openpi-dataset#8]
The statistic in this repo seems to be different from it reported in the paper. 
"Id_answers.jsonl" has a total of 29665 status changes, while the number in the paper is 29928.
Is the dataset slightly different from the dataset used in the paper?

**Comment by wangbo9719** [comment]
I found that the statistic of "formatted_for_gpt2" is same as the reported numbers in the paper. 
But why they are different from the gold version? 
For example, in Line 366, the answers in formatted data are: 

> {"id": "www.wikihow.com/Make-a-Pipe-Cleaner-Chair||2", "question": "Bend two same-colored pipe cleaners into half square shapes. Loop the end of a pipe cleaner above the front leg. Now, what happens?", "answer": "state of pipe cleaners were separate before and joined afterwards, shape of pipe cleaner was unlooped before and looped afterwards, structure status of structure was disassembled before and assembled afterwards, shape of pipe cleaner ends were straight before and curled afterwards, composition of pipe cleaners were solitary before and bound together afterwards, shape of the pipe cleaner was straight before and looped afterwards, shape of wire was straight before and bent afterwards"}

But in gold version, the answer is None:

> {"id": "www.wikihow.com/Make-a-Pipe-Cleaner-Chair||2", "answers": []}

**Comment by nikett** [comment]
Thanks for reporting this bug. Sorry for the very late response, my notification settings were incorrect and I didn't observe this issue until two days ago. 
 
The following commit fixes this metadata generation bug, caused by some incomplete Turker supplied answers (e.g., size of mango or mango was raw before and r... incomplete answers). The script failed on the entire entry (and no answer was recorded for this step/ entry). To fix this, we ensure that like the gpt2_dataset , the metadata generators also ignore these incomplete answers, and gpt2_dataset are carried over to the openpi v1.1 dataset.

When you match 29928 , please note that the gpt2 dataset contains "There will be no change" string but it equivalent to an empty array [] in the id_answers dataset). The current version fuses the ques, ans, ques_metadata, ans_metadata data into one jsonl entry.

https://github.com/allenai/openpi-dataset/tree/main/data/gold-v1.1

**Comment by wangbo9719** [comment]
Thanks for answering.
